---
- name: "Setup Linux"
  import_tasks: "setup_linux.yml"

- name: "Install Redis"
  import_tasks: "install_redis.yml"

- name: "Generate and copy redis.conf file"
  template:
    src: "redis_{{ redis_version }}.conf.j2"
    dest: "/etc/redis/redis.conf"
    owner: "redis"
    group: "redis"
    mode: "0640"

- name: "Enable and restart Redis"
  service:
    name: "redis-server"
    enabled: true
    state: "restarted"
...