---
- name: "Setup Linux"
  import_tasks: "setup_linux.yml"

- name: "Install Redis"
  import_tasks: "install_redis.yml"

- name: "Generate and copy redis.conf file"
  template:
    src: "redis_{{ redis_version }}.conf.j2"
    dest: "/etc/redis/redis.conf"
    owner: "redis"
    group: "redis"
    mode: "0640"

- name: "Create /utils directory"
  file:
    path: "/etc/redis/utils"
    state: "directory"
    owner: "redis"
    group: "redis"
    mode: "0640"

- name: "Copy create-cluster.sh file"
  copy:
    src: "create-cluster_{{ redis_version }}.sh"
    dest: "/etc/redis/utils/create-cluster.sh"
    owner: "redis"
    group: "redis"
    mode: "0700"

- name: "Enable and restart Redis"
  service:
    name: "redis-server"
    enabled: true
    state: "restarted"
...