---
- name: "Install Sentinel"
  apt:
    update_cache: true
    name:
      - "redis-sentinel=6:{{ redis_version }}-1rl1~bullseye1"

- name: "Generate and copy sentinel.conf file"
  template:
    src: "sentinel_{{ sentinel_version }}.conf.j2"
    dest: "/etc/redis/sentinel.conf"
    owner: "redis"
    group: "redis"
    mode: "0640"

- name: "Enable and restart Sentinel"
  service:
    name: "redis-sentinel"
    enabled: true
    state: "restarted"
...