# https://hub.docker.com/r/redis/redisinsight
# > docker compose up
# http://localhost:5540/
# Aggiungere il database 192.168.56.11:6379
# utente: default
# password: foobar

services:
  redisinsight:
    image: "redis/redisinsight:latest"
    volumes:
      - "redisinsight:/data"
    ports:
      - "5540:5540"
volumes:
  redisinsight: