# https://hub.docker.com/r/redis/redisinsight
# > docker compose up
# http://localhost:5540/

services:
  redisinsight:
    image: "redis/redisinsight:latest"
    volumes:
      - "redisinsight:/data"
    ports:
      - "5540:5540"
    environment:
      - REDIS_HOST=192.168.56.11
      - REDIS_PORT=6379

volumes:
  redisinsight: