---
- name: "Setup"
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:
  - name: "Update VM"
    apt:
      update_cache: true
      upgrade: true
      autoremove: true
      purge: true

  roles:
    - role: "redis"
      redis_version: "7.4.1"
      redis_bind: "0.0.0.0"
      redis_protected_mode: "no"

    - role: "sentinel"
      sentinel_version: "7.4.1"
...